---

- name: Install Git
  apt: pkg=git update_cache=yes state=present
  sudo: yes

- name: Install PCRE library
  apt: pkg=libpcre3-dev state=present
  sudo: yes

- name: Install OpenSSL development headers
  apt: pkg=libssl-dev state=present
  sudo: yes

- name: Install build tools
  apt: pkg=build-essential state=present
  sudo: yes

- name: Create MH parent dir
  file: path={{oc_parent_dir}}/ owner="{{opencast_user}}" group="{{opencast_group}}" state=directory recurse=true
  sudo: true

- name: Checking if nginx binary exists
  stat: path={{oc_tools_dir}}/nginx/sbin/nginx
  register: nginxpresent

- include: ../../nginx-stop/tasks/main.yml

- include: ../../common/tasks/create_tools_bin.yml

- name: Create MH shared dir
  file: path={{oc_work_dir}} owner="{{opencast_user}}" group="{{opencast_group}}" state=directory

  #Mount NFS
- include: ../../common/tasks/nfs_mount.yml
  when: inventory_hostname in groups['streamer']

- name: Create MH streams dir
  file: path={{oc_streaming_dir}} owner="{{opencast_user}}" group="{{opencast_group}}" state=directory
  when: inventory_hostname in groups['streamer']

- name: Downloading nginx
  get_url: url=http://nginx.org/download/nginx-{{nginx_version}}.tar.gz
           dest={{oc_tool_archive_dir}}/nginx-{{nginx_version}}.tar.gz
           force=no

- name: Decompressing nginx
  unarchive: src={{oc_tool_archive_dir}}/nginx-{{nginx_version}}.tar.gz dest={{oc_tools_dir}} copy=no
            creates={{nginx_home}}

- name: Downloading RTMP module for nginx
  git: repo=https://github.com/arut/nginx-rtmp-module
       dest={{oc_tools_dir}}/nginx-rtmp-module
       update=yes
  when: inventory_hostname in groups['streamer']

- name: Preparing to build nginx
  shell: ./configure --prefix={{oc_tools_dir}}/nginx --pid-path=/var/run/nginx.pid
         chdir={{oc_tools_dir}}/nginx-1.2.4
  when: inventory_hostname not in groups['streamer']


- name: Preparing to build nginx with streaming components
  shell: ./configure --add-module={{oc_tools_dir}}/nginx-rtmp-module --prefix={{oc_tools_dir}}/nginx --pid-path=/var/run/nginx.pid
         chdir={{oc_tools_dir}}/nginx-1.2.4
  when: inventory_hostname in groups['streamer']

- name: Building nginx
  shell: make
         chdir={{oc_tools_dir}}/nginx-1.2.4

- name: Installing nginx
  shell: make install
         chdir={{oc_tools_dir}}/nginx-1.2.4

- name: Configuring nginx for http
  template: src=nginx-http.conf dest={{oc_tools_dir}}/nginx/conf/nginx.conf
  when: inventory_hostname not in groups['streamer'] and build_nginx

- name: Configuring nginx for http and streaming
  template: src=nginx-streaming.conf dest={{oc_tools_dir}}/nginx/conf/nginx.conf
  when: inventory_hostname in groups['streamer'] and build_nginx

- name: Configuring nginx init script
  template: src=nginx dest=/etc/init.d/nginx mode=0755
  when: build_nginx
  sudo: yes

- name: Setting nginx to start on boot
  service: name=nginx state=stopped enabled=yes
  when: build_nginx
  sudo: yes
