---

- include: ../../opencast-stop/tasks/main.yml

- name: Stop and disable Matterhorn
  service: name=opencast state=stopped enabled=no
  sudo: yes
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True

- name: Removing Matterhorn init script
  file: path=/etc/init.d/opencast state=absent
  sudo: yes
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True

- name: Unmount NFS Mounts
  mount: name={{oc_work_dir}} src={{nfs_server}}:{{oc_work_dir}} fstype=nfs state=unmounted opts=rw,sync
  sudo: yes
  when: nfs_server is defined and 'fileserver' not in group_names

- name: Removing Matterhorn log directory
  file: path={{oc_log_dir}} state=absent
  sudo: yes
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True

- name: Remove Matterhorn configuration directory
  file: path={{oc_config_dir}} state=absent
  sudo: yes
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True

- name: Detecting presence of Maven repository data
  stat: path={{m2_repo}}
  register: mavenpresent

- name: Preserving Maven repository directory, if any
  shell: mv {{m2_repo}} {{m2_backup_dir}}
  sudo: yes
  when: "'fileserver' in group_names and mavenpresent.stat.exists is defined and mavenpresent.stat.exists == True"

- name: Wipe Matterhorn root directory
  file: path={{oc_parent_dir}} state=absent
  sudo: yes
