---

- name: Checking if Matterhorn exists
  stat: path=/etc/init.d/opencast
  register: opencastpresent

- name: Stopping Matterhorn
  service: name=opencast state=stopped
  sudo: yes
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True
