---
# This playbook deploys a full Opencast cluster

- hosts: mysql
  user: "{{opencast_user}}"

  roles:
    - mysql-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml


- hosts: activemq
  user: "{{opencast_user}}"

  roles:
    - activemq-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: admin
  user: "{{opencast_user}}"

  roles:
    - maven
    - ffmpeg
    - opencast-base
    - opencast-core
    - admin-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml
    - roles/admin-build/vars/admin-all-in-one.yml


- hosts: streamer
  user: "{{opencast_user}}"

  roles:
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml


- hosts: solr
  user: "{{opencast_user}}"

  roles:
    - solr-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml


- hosts: engage
  user: "{{opencast_user}}"

  roles:
    - maven
    - opencast-base
    - opencast-core
    - node.js-build
    - engage-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml
    - roles/engage-build/vars/engage-all-in-one.yml


- hosts: worker
  user: "{{opencast_user}}"

  roles:
    - maven
    - ffmpeg
    - hunspell
    - sox
    - tesseract
    - opencast-base
    - opencast-core
    - worker-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml
    - roles/worker-build/vars/worker-all-in-one.yml


- hosts: capture
  user: "{{opencast_user}}"

  roles:
    - pyca-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/all-in-one.yml
    - group_vars/pyca.yml
