---
# This playbook deploys a full Opencast cluster

- hosts: opencast
  become: yes
  tasks:
    - name: Add opencast group
      group:
        name: opencast
        state: present

    - name: Add opencast user
      user:
        name: opencast
        state: present
        group: opencast
        groups: root
        password: opencast
      

- hosts: fileserver
  user: "{{opencast_user}}"
  roles:
    - nfs-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: mysql
  user: "{{opencast_user}}"
  roles:
    - mysql-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
  sudo: yes

- hosts: activemq
  user: "{{opencast_user}}"
  roles:
    - activemq-package-install
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
  sudo: yes


- hosts: admin
  user: "{{opencast_user}}"
  roles:
    - ffmpeg-package-install
    - matterhorn-package-install
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/admin-build/vars/admin.yml
  sudo: yes 

- hosts: streamer
  user: "{{opencast_user}}"
  roles:
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
  sudo: yes 

- hosts: engage
  user: "{{opencast_user}}"
  roles:
    - ffmpeg-package-install
    - matterhorn-package-install
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/engage-build/vars/engage.yml
  sudo: yes 

- hosts: solr
  user: "{{opencast_user}}"
  roles:
    - solr-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
  sudo: yes 

- hosts: worker
  user: "{{opencast_user}}"
  sudo: yes 
  roles:
    - ffmpeg-package-install
    - matterhorn-package-install
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
