---
# This playbook deploys a full Opencast cluster

- hosts: opencast
  become: yes
  tasks:
    - name: Add opencast group
      group:
        name: opencast
        state: present

    - name: Add opencast user
      user:
        name: opencast
        state: present
        group: opencast
        groups: root
        password: opencast
      

- hosts: fileserver
  user: "{{opencast_user}}"

  roles:
    - nfs-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: mysql
  user: "{{opencast_user}}"

  roles:
    - mysql-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: activemq
  user: "{{opencast_user}}"

  roles:
    - activemq-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: admin
  user: "{{opencast_user}}"

  roles:
    - maven
    - matterhorn-base
    - matterhorn-core
    - admin-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/admin-build/vars/admin.yml


- hosts: streamer
  user: "{{opencast_user}}"

  roles:
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: solr
  user: "{{opencast_user}}"

  roles:
    - solr-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: engage
  user: "{{opencast_user}}"

  roles:
    - maven
    - matterhorn-base
    - matterhorn-core
    - node.js-build
    - engage-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/engage-build/vars/engage.yml


- hosts: ingest
  user: "{{opencast_user}}"

  roles:
    - maven
    - matterhorn-base
    - matterhorn-core
    - ingest-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/ingest-build/vars/ingest.yml


- hosts: worker
  user: "{{opencast_user}}"

  roles:
    - maven
    - ffmpeg
    - hunspell
    - sox
    - tesseract
    - matterhorn-base
    - matterhorn-core
    - worker-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - roles/worker-build/vars/worker.yml


- hosts: capture
  user: "{{opencast_user}}"

  roles:
    - pyca-build
    - nginx-build
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - group_vars/pyca.yml
