---
# This playbook starts a full Opencast cluster

- hosts: solr
  user: "{{opencast_user}}"

  roles:
    - solr-start
  vars_files:
    - group_vars/common.yml


- hosts: activemq
  user: "{{opencast_user}}"

  roles:
    - activemq-start
  vars_files:
    - group_vars/common.yml


- hosts: admin
  user: "{{opencast_user}}"

  roles:
    - nginx-start
    - opencast-start
  vars_files:
    - group_vars/common.yml


- hosts: opencast
  user: "{{opencast_user}}"

  roles:
    - nginx-start
    - opencast-start
  vars_files:
    - group_vars/common.yml


- hosts: capture
  user: "{{opencast_user}}"

  roles:
    - pyca-start
  vars_files:
    - group_vars/common.yml
