---
# This playbook stops a full Opencast cluster

- hosts: capture
  user: "{{opencast_user}}"

  roles:
    - pyca-stop
  vars_files:
    - group_vars/common.yml


- hosts: opencast
  user: "{{opencast_user}}"

  roles:
    - opencast-stop
    - nginx-stop
  vars_files:
    - group_vars/common.yml


- hosts: activemq
  user: "{{opencast_user}}"

  roles:
    - activemq-stop
  vars_files:
    - group_vars/common.yml


- hosts: solr
  user: "{{opencast_user}}"

  roles:
    - solr-stop
  vars_files:
    - group_vars/common.yml
