---
# This playbook destroys a full Opencast cluster, data and binaries included

- include: stop.yml

- hosts: capture
  user: "{{opencast_user}}"

  roles:
    - nginx-wipe
    - pyca-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
    - group_vars/pyca.yml


- hosts: opencast
  user: "{{opencast_user}}"

  roles:
    - opencast-stop
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: activemq
  user: "{{opencast_user}}"

  roles:
    - activemq-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: solr
  user: "{{opencast_user}}"

  roles:
    - solr-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: mysql
  user: "{{opencast_user}}"

  roles:
    - mysql-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml


- hosts: all
  user: "{{opencast_user}}"

  roles:
    - nginx-wipe
    - opencast-wipe
  vars_files:
    - group_vars/common.yml
    - group_vars/cluster.yml
