---

- name: Checking if Opencast exists
  stat: path=/etc/init.d/opencast
  register: opencastpresent

- name: Install httplib2
  apt: pkg=python-httplib2 state=present
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True
  sudo: yes

- name: Starting Opencast
  service: name=opencast state=started
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True
  sudo: yes

- name: Waiting on Opencast to be available
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True
  wait_for: port=8080

- name: Waiting until Opencast page contains `Opencast Video Capture Software` string
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True and 'admin' in group_names
  uri: url=http://{{ inventory_hostname }} return_content=true
  register: response
  until: response.content is defined and response.content | search("Opencast Video Capture Software")
  delay: 10
  retries: 12

- name: Waiting until Opencast page contains `Welcome to Opencast` string
  when: opencastpresent.stat.exists is defined and opencastpresent.stat.exists == True and 'admin' not in group_names
  uri: url=http://{{ inventory_hostname }} return_content=true
  register: response
  until: response.content is defined and response.content | search("Welcome to Opencast")
  delay: 10
  retries: 12

