---

- name: Opencast Admin install
  yum: update_cache=yes name={{ item }} state=latest
  with_items:
    - opencast{{ opencast_version }}-admin
  when: inventory_hostname in groups['admin']

- name: Opencast presentation install
  yum: update_cache=yes name={{ item }} state=latest
  with_items:
    - opencast{{ opencast_version }}-presentation
  when: inventory_hostname in groups['presentation']

- name: Opencast Worker install
  yum: update_cache=yes name={{ item }} state=latest
  with_items:
    - opencast{{ opencast_version }}-worker
  when: inventory_hostname in groups['worker']
