---

- include: ../../common/tasks/create_tools_bin.yml

- name: Uninstall packaged Maven
  apt: pkg=maven state=absent
  sudo: yes

- name: Download Maven
  get_url: url={{mvn_url}}
           dest={{oc_tool_archive_dir}}/apache-maven-{{mvn_version}}-bin.tar.gz
           force=no

- name: Fetching and decompressing Maven
  unarchive: src={{oc_tool_archive_dir}}/apache-maven-{{mvn_version}}-bin.tar.gz dest={{oc_tools_dir}} copy=no
            creates={{mvn_home}}

- name: Symlinking Maven into tools directory
  file: src={{mvn_home}}/bin/mvn dest={{oc_tools_bin}}/mvn state=link

- name: Configuring Maven for Matterhorn
  lineinfile: dest=/home/{{opencast_user}}/.bash_aliases
              state=present
              create=yes
              regexp='export MAVEN_OPTS=.*$'
              line='export MAVEN_OPTS="{{maven_opts}}"'

- name: Detecting backup M2 repository
  stat: path={{m2_backup_dir}}
  register: repository_exists

- name: Restoring Maven repository
  shell: mv {{m2_backup_dir}} {{m2_repo}}
  sudo: yes
  when: repository_exists.stat.islink is defined and repository_exists.stat.islink == True

- name: Repairing Maven repository permissions
  file: path={{m2_repo}}../ owner={{opencast_user}} group={{opencast_group}} state=directory recurse=true
  when: repository_exists.stat.islink is defined and repository_exists.stat.islink == True
