---

- include: ../../common/tasks/checkout_oc.yml

- name: Creating config directory
  file: src={{oc_base_dir}}/etc dest={{oc_config_dir}} state=link
  sudo: yes

- include: ../../common/tasks/clean_oc_logs.yml

- name: Fix logging directory permissions and linking
  file: src={{oc_log_dir}} dest={{oc_base_dir}}/logs owner={{opencast_user}} group={{opencast_group}} state=link
  sudo: true

- name: Configure init scripts
  template: src=etc-opencast-service.conf dest={{oc_base_dir}}/etc/service.conf

- name: Install the init scripts
  shell: install -p -D -m 0755 etc-init.d-opencast  /etc/init.d/opencast
         chdir={{oc_base_dir}}/docs/scripts/init/system/
  sudo: yes

- name: Install the system script
  shell: install -p -D -m 0755 usr-sbin-opencast    /usr/sbin/opencast
         chdir={{oc_base_dir}}/docs/scripts/init/system/
  sudo: yes

- name: Install the man-page
  shell: install -p -D -m 0644 opencast.8  /usr/share/man/man8 && rm -f opencast.8
         chdir={{oc_base_dir}}/docs/scripts/init/system/
  sudo: yes

- name: Configure config.properties
  template: src=config.properties dest={{oc_base_dir}}/etc/

- name: Configure organization profile
  template: src=org.opencastproject.organization-oc_default_org.cfg dest={{oc_base_dir}}/etc/load/

- name: Configure service registry
  template: src=org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.properties dest={{oc_base_dir}}/etc/services/

- name: Set Matterhorn start on boot
  service: name=opencast enabled=yes
  sudo: yes
