---

- name: Install NFS server
  #Debian
  yum: pkg=nfs-kernel-server state=present
  sudo: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  #RHEL
  yum: pkg=nfs-utils state=present
  sudo: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Create MH storage dir
  file: path={{ oc_work_dir }} owner="{{opencast_user}}" group="{{opencast_group}}" state=directory
  sudo: yes

- name: Fix MH parent dir permissions
  file: path={{oc_parent_dir}}/ owner="{{opencast_user}}" group="{{opencast_group}}" state=directory recurse=true
  sudo: true

- name: Setup NFS Exports
  nfsexport: path={{oc_work_dir}} clients="{{nfs_exports}}" options="rw,no_subtree_check"
  sudo: yes

- name: Check for Portmap
  stat: path=/etc/init.d/portmap
  register: portmap

- name: Restart portmap
  service: name=portmap state=restarted enabled=yes
  when: portmap.stat.exists is defined and portmap.stat.exists == True
  sudo: yes

- name: Restart NFS
  #Debian
  service: name=nfs-kernel-server state=restarted enabled=yes
  sudo: yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  #RHEL
  service: name=nfs-utils state=restarted enabled=yes
  sudo: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
