---

- include: ../../common/tasks/create_tools_bin.yml

- name: Downloading static FFmpeg
  get_url: url={{ffmpeg_static}}
           dest={{oc_tool_archive_dir}}/ffmpeg-release-64bit-static.tar.xz
           force=no

- name: Decompressing FFmpeg
  unarchive: src={{oc_tool_archive_dir}}/ffmpeg-release-64bit-static.tar.xz dest={{oc_tools_dir}} copy=no

#Oh man this is lame, but otherwise we'd need something like
#https://github.com/ansible/ansible/issues/10115
#to work
- name: Determining FFmpeg version
  shell: ls {{oc_tools_dir}} | grep ffmpeg | head -n 1
  register: ffmpeg_version

- name: Symlinking FFmpeg
  file: src={{oc_tools_dir}}/{{item}}/ffmpeg dest={{oc_tools_bin}}/ffmpeg state=link
  with_items: ffmpeg_version.stdout_lines

- name: Symlinking FFprobe
  file: src={{oc_tools_dir}}/{{item}}/ffprobe dest={{oc_tools_bin}}/ffprobe state=link
  with_items: ffmpeg_version.stdout_lines
