---

- include: ../../common/tasks/create_tools_bin.yml

- name: Downloading Node.js
  get_url: url=https://nodejs.org/dist/{{node_version}}/node-{{node_version}}-linux-x64.tar.gz
           dest={{oc_tools_dir}}/node-{{node_version}}-linux-x64.tar.gz
           force=no

- name: Decompressing Node.js
  unarchive: src={{oc_tools_dir}}/node-{{node_version}}-linux-x64.tar.gz dest={{oc_tools_dir}} copy=no
             creates={{node_home}}

- name: Symlinking node
  file: src={{node_home}}/bin/node dest={{oc_tools_bin}}/node state=link

- name: Symlinking NPM
  file: src={{node_home}}/bin/npm dest={{oc_tools_bin}}/npm state=link
