---

- name: Install Java
  apt: pkg=openjdk-7-jdk update_cache=yes state=present
  sudo: yes

- name: Removing pre-1.7 Java JDK
  apt: pkg=openjdk-6-jdk state=absent
  sudo: yes

- name: Removing pre-1.7 Java JRE
  apt: pkg=openjdk-6-jre,openjdk-6-jre-headless state=absent
  sudo: yes

- name: Install Git
  apt: pkg=git-core state=present
  sudo: yes

- name: Create MH parent dir
  file: path={{ oc_parent_dir }} owner={{opencast_user}} group={{opencast_group}} state=directory
  sudo: yes

- name: Fix MH parent dir permissions
  file: path={{oc_parent_dir}}/ owner={{opencast_user}} group={{opencast_group}} state=directory recurse=true
  sudo: true

- name: Create MH shared dir
  file: path={{oc_work_dir}} owner={{opencast_user}} group={{opencast_group}} state=directory

- include: ../../common/tasks/create_tools_bin.yml

#From https://coderwall.com/p/ynvi0q
- name: Add tools to path
  lineinfile: dest=/etc/environment
              state=present
              backrefs=yes
              regexp='PATH=(["]*)((?!.*?{{oc_tools_bin}}).*?)(["]*)$'
              line="PATH=\1\2:{{oc_tools_bin}}\3"
  sudo: yes

- name: Checking if Opencast is already installed
  stat: path=/etc/init.d/opencast
  register: opencast_installed

- name: Stopping Opencast
  service: name=opencast state=stopped
  when: opencast_installed.stat.exists is defined and opencast_installed.stat.exists == True
  sudo: yes

- include: ../../common/tasks/clone_oc.yml

- name: Check if Opencast is symlinked
  stat: path={{oc_parent_dir}}/felix
  register: felix_done

- name: Symlinking Opencast
  file: src=opencast dest=felix state=link
         chdir={{oc_parent_dir}}
  ignore_errors: True
  when: felix_done.stat.islink is defined and felix_done.stat.islink == True
