---
- include: clean_oc.yml

- name: Fix MH parent dir permissions
  file: path={{oc_parent_dir}}/ owner="{{opencast_user}}" group="{{opencast_group}}" state=directory recurse=true
  sudo: true

- name: Build with tests
  shell: MAVEN_OPTS="{{maven_opts}}" PATH="{{oc_tools_bin}}:$PATH" mvn clean install -DdeployTo="{{oc_base_dir}}" -P "{{oc_build_profile}}" -Dcheckstyles.skip="{{checkstyle_skip}}"
         chdir={{oc_base_dir}}
  when: not skip_tests and do_build

- name: Build without tests
  shell: MAVEN_OPTS="{{maven_opts}}" PATH="{{oc_tools_bin}}:$PATH" mvn clean install -DdeployTo="{{oc_base_dir}}" -P "{{oc_build_profile}}" -Dcheckstyles.skip="{{checkstyle_skip}}" -DskipTests
         chdir={{oc_base_dir}}
  when: skip_tests and do_build

- name: Stamping built Matterhorn version to disk
  shell: 'echo "`cd {{oc_base_dir}} && git rev-parse HEAD` from {{git_repo_location}} / {{oc_version}}" > {{oc_base_dir}}/build_version.txt'
