---

- name: Clean Opencast log
  file: path={{oc_log_dir}} state=absent
  sudo: yes

- name: Create logging directory
  file: path={{oc_log_dir}} state=directory owner={{opencast_user}} group={{opencast_group}}
  sudo: yes
