---

- name: Create MH parent dir
  file: path={{ oc_parent_dir }} owner={{opencast_user}} group={{opencast_group}} state=directory
  sudo: yes

- name: Pushing SSH configs
  copy: src=../../../group_vars/ssh/ dest=/home/{{opencast_user}}/.ssh mode=600

- name: Ensuring Git is installed
  apt: pkg=git state=present
  sudo: yes

- name: Cloning Opencast
  git: repo={{git_repo_location}}
       dest={{oc_base_dir}}
       update=yes
       version={{oc_version}}
       force=yes

- include: checkout_oc.yml
