---

- name: Install NFS client Debian
  apt: pkg=nfs-common state=present
  sudo: yes
  when: nfs_server is defined and 'fileserver' not in group_names
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install NFS client RHEL
  yum:
    name: nfs-utils
    state: present
  sudo: yes
  when: nfs_server is defined and 'fileserver' not in group_names
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Setup NFS Mounts
  mount: name={{oc_work_dir}} src={{nfs_server}}:{{oc_work_dir}} fstype=nfs state=mounted opts=ro,async,vers=3
  sudo: yes
  when: nfs_server is defined and 'fileserver' not in group_names
